-- Exercicios da 8º aula SQL - 2018/2019
-- NOTA: Exercicios da 7º aula SQL - 2018/2019 ---> Power Designer

-- ex 1
CREATE TABLE AUTORES2 (
    CODIGO_AUTOR NUMBER(4) CONSTRAINT PK_AUTORES2 PRIMARY KEY,
    NOME VARCHAR(30) NOT NULL CONSTRAINT CK_NOME_M CHECK(NOME=UPPER(NOME)),
    N_CONTRIBUINTE NUMBER(9) NOT NULL CONSTRAINT UK_NIF UNIQUE,
    MORADA VARCHAR(50),
    IDADE NUMBER(4) CONSTRAINT CK_IDADE CHECK( IDADE > 0 AND IDADE < 200 ),
    SEXO CHAR(1),
    NACIONALIDADE VARCHAR(20),
    GENERO_PREFERIDO VARCHAR(20)
    );


-- ex 2 

CREATE TABLE AVALIACOES(
    CODIGO_CLIENTE NUMBER (4) ,
    CODIGO_LIVRO NUMBER (4),
    NOTA NUMBER (1) CONSTRAINT CK_NOTA CHECK(NOTA>=1 AND NOTA<=5),
    CONSTRAINT PK_AVALIACOES PRIMARY KEY (CODIGO_LIVRO, CODIGO_CLIENTE),
    CONSTRAINT FK_AVAL_LIVRO FOREIGN KEY (CODIGO_LIVRO) 
                             REFERENCES LIVROS (CODIGO_LIVRO),
    CONSTRAINT FK_AVAL_CLIENTE FOREIGN KEY (CODIGO_CLIENTE) 
                               REFERENCES CLIENTES (CODIGO_CLIENTE)
    );
    
    
-- ex 3 

CREATE TABLE LIVROS_BACKUP AS
  SELECT CODIGO_LIVRO,
     CODIGO_EDITORA,
     CODIGO_AUTOR,
     TITULO,
     ISBN,
     UPPER(GENERO) AS GENERO,
     PRECO_TABELA,
     PAGINAS,
     QUANT_EM_STOCK,
     UNIDADES_VENDIDAS,
     DATA_EDICAO
    FROM LIVROS ;

-- ex 4 
 ALTER TABLE LIVROS_BACKUP
     ADD CONSTRAINT PK_LIVRO_BACKUP PRIMARY KEY (CODIGO_LIVRO);
     
ALTER TABLE LIVROS_BACKUP
     ADD CONSTRAINT KEY_LIVBK_AUTORES FOREIGN KEY(CODIGO_AUTOR)
     REFERENCES AUTORES (CODIGO_AUTOR);
     
ALTER TABLE LIVROS_BACKUP
     ADD CONSTRAINT KEY_LIVBK_EDITORAS FOREIGN KEY(CODIGO_EDITORA)
     REFERENCES EDITORAS (CODIGO_EDITORA);
     
ALTER TABLE LIVROS_BACKUP
     ADD CONSTRAINT CK_GENERO_MAIS CHECK(GENERO = UPPER (GENERO));
   
     
-- ex 5 