-- Exercicios da 6º aula SQL - 2018/2019
-- NOTA: Exercicios da 7º aula SQL - 2018/2019 ---> Power Designer

-- ex 1
SELECT LLIVROS AS "Total de Livros",
       AAUTORES AS "Total de Autores",
       EEDITORAS AS "Total ed Editoras"
FROM 
    ( SELECT COUNT(CODIGO_LIVRO) LLIVROS
      FROM LIVROS ) LI,
    ( SELECT COUNT(CODIGO_AUTOR) AAUTORES
      FROM AUTORES ) AU,
    ( SELECT COUNT(CODIGO_EDITORA) EEDITORAS
      FROM EDITORAS ) ED ;
      
--  ex 2 
SELECT 'O autor ' || NOME ||
       ' escreveu ' || QUANT_LIVROS || 
       ' livro(s) e ' || QUANT_EDIT || 
       ' sob a alçada da editora FCA-EDITORA' AS "Resultado"
FROM
    ( SELECT A.NOME, COUNT(L.CODIGO_LIVRO) QUANT_LIVROS
      FROM AUTORES A, LIVROS L
      WHERE A.CODIGO_AUTOR=L.CODIGO_AUTOR
      GROUP BY A.NOME
      ORDER BY A.NOME) TAB_AUTOR ,
    ( SELECT A.NOME AS IDENT, COUNT(L.CODIGO_LIVRO) QUANT_EDIT
      FROM LIVROS L, AUTORES A , EDITORAS E 
      WHERE L.CODIGO_EDITORA = E.CODIGO_EDITORA
      AND L.CODIGO_AUTOR = A.CODIGO_AUTOR
      AND E.NOME = 'FCA - EDITORA'
      GROUP BY A.NOME ) TAB_EDITORA
WHERE TAB_AUTOR.NOME = TAB_EDITORA.IDENT;

--  ex 3
SELECT A.NOME AS NOME , L.TITULO AS TITULO, TOTAL_FCA AS "LIVROS FCA", TOTAL_LIVROS AS "Total de Livros"
FROM AUTORES A , LIVROS L , EDITORAS E,
    (SELECT A.NOME AS N2, COUNT(CODIGO_LIVRO) TOTAL_FCA
     FROM LIVROS L, EDITORAS E , AUTORES A 
     WHERE L.CODIGO_EDITORA = E.CODIGO_EDITORA
     AND L.CODIGO_AUTOR = A.CODIGO_AUTOR 
     AND E.NOME = 'FCA - EDITORA'
     GROUP BY A.NOME) TAB_TOTAL_FCA,
        (SELECT A.NOME AS N3, COUNT(CODIGO_LIVRO) TOTAL_LIVROS
         FROM LIVROS L, AUTORES A 
         WHERE  L.CODIGO_AUTOR = A.CODIGO_AUTOR 
         GROUP BY A.NOME
         ORDER BY A.NOME ) TAB_TOTAL_LIVROS
WHERE L.CODIGO_EDITORA = E.CODIGO_EDITORA
AND L.CODIGO_AUTOR = A.CODIGO_AUTOR
AND L.PRECO_TABELA = (SELECT MAX(PRECO_TABELA)
                      FROM LIVROS L , EDITORAS E 
                      WHERE E.NOME = 'FCA - EDITORA')
AND A.NOME=TAB_TOTAL_FCA.N2
AND A.NOME=TAB_TOTAL_LIVROS.N3;


-- ex 4 

SELECT DISTINCT TAB1.NOME NOME,
        NVL(GPREF,0) "Género Preferido", 
        N_LIVROS "Total de Livros" 
FROM 
    (SELECT AUTORES.NOME , COUNT(LIVROS.CODIGO_AUTOR) N_LIVROS
     FROM AUTORES, LIVROS
     WHERE AUTORES.CODIGO_AUTOR = LIVROS.CODIGO_AUTOR
     GROUP BY AUTORES.NOME) TAB1,
        (SELECT NOME, COUNT(TITULO) GPREF
         FROM AUTORES, LIVROS
         WHERE AUTORES.CODIGO_AUTOR = LIVROS.CODIGO_AUTOR
         AND AUTORES.GENERO_PREFERIDO = LIVROS.GENERO
         GROUP BY NOME) TAB2
WHERE TAB1.NOME = TAB2.NOME(+)
ORDER BY NOME;


-- ex 5 
