------ AULA 10 2016/2017

S1
-- 1b
CREATE TABLE CLIENTES_BACKUP
AS 
  SELECT *
  FROM CLIENTES;

--1c
SELECT *
FROM CLIENTES_BACKUP;

--1d
INSERT INTO CLIENTES_BACKUP (CODIGO_CLIENTE, NOME, N_CONTRIBUINTE, MORADA, TELEFONE)
VALUES (11, 'Joao Moreira', 1020304, 'Rua Palheiros das Ondas –
1030 775 Santarém',  243123456);

--1e
SELECT *
FROM CLIENTES_BACKUP; -- altera com 1d

--1g
SELECT *
FROM CLIENTES_BACKUP; -- nao altera com 1f

--1h
COMMIT;

--2a
UPDATE CLIENTES_BACKUP
SET TELEFONE = 239555555
WHERE CODIGO_CLIENTE = 8;

SELECT *
FROM CLIENTES_BACKUP;

--2d
COMMIT;

SELECT *
FROM CLIENTES_BACKUP;

--2e
--Como o commit é feito aqui as alteraçoes de S2 nao passam para aqui.
--Apenas passam as daqui para lá

--3b
DROP TABLE FUNCIONARIO; 
-- "aquisição de recurso ocupado com NOWAIT especificado ou tempo de espera esgotado"

--3c
INSERT INTO FUNCIONARIO (N_CONTRIBUINTE, NOME, TELEFONE)
VALUES(987654321, 'Joaquim Almeida', 239534123); --computador morre

--3e
SELECT *
FROM FUNCIONARIO;

--4a
UPDATE CLIENTES_BACKUP
SET TELEFONE = 239111111
WHERE CODIGO_CLIENTE = 1;

--4d
UPDATE CLIENTES_BACKUP
SET N_CONTRIBUINTE = 959595959
WHERE CODIGO_CLIENTE = 2;

--4e
--computador morreu

S2
--1c
SELECT *
FROM CLIENTES_BACKUP;

--1e
SELECT *
FROM CLIENTES_BACKUP; -- nao altera com 1d

--1f
UPDATE CLIENTES_BACKUP
SET N_CONTRIBUINTE = 999999999
WHERE CODIGO_CLIENTE = 1;

--1g
SELECT *
FROM CLIENTES_BACKUP; -- altera com 1f

--1i
ROLLBACK;

SELECT *
FROM CLIENTES_BACKUP;

--2b
UPDATE CLIENTES_BACKUP
SET NOME = 'Manuel Moreira'
WHERE CODIGO_CLIENTE = 11;

SELECT *
FROM CLIENTES_BACKUP;

--2c
UPDATE CLIENTES_BACKUP
SET MORADA = 'Rua Ferreira Borges – 3000 179 Coimbra'
WHERE CODIGO_CLIENTE = 8;

SELECT *
FROM CLIENTES_BACKUP;

--2d
SELECT *
FROM CLIENTES_BACKUP;

--2e
CREATE TABLE FUNCIONARIO
    (N_CONTRIBUINTE  NUMBER(9)  CONSTRAINT pk_ncontribuinte PRIMARY KEY,
    NOME  VARCHAR2(80),
    TELEFONE  NUMBER(9));

--3a
INSERT INTO FUNCIONARIO (N_CONTRIBUINTE, NOME, TELEFONE)
VALUES(987654321, 'Joaquim Almeida', 239534123);

SELECT *
FROM FUNCIONARIO;

--3d
COMMIT;

--3e
DROP TABLE FUNCIONARIO;

--4b
UPDATE CLIENTES_BACKUP
SET TELEFONE = 239222222
WHERE CODIGO_CLIENTE = 2;

--4c
UPDATE CLIENTES_BACKUP
SET N_CONTRIBUINTE = 717171717
WHERE CODIGO_CLIENTE = 1;

--4e
--"detecção de impasse ao esperar pelo recurso"