------ AULA 2 2016/2017


SELECT TITULO
FROM LIVROS, AUTORES
WHERE LIVROS.CODIGO_AUTOR = AUTORES.CODIGO_AUTOR
AND NOME='Cláudio Tereso' AND GENERO='Policial';

SELECT TITULO
FROM LIVROS, AUTORES
WHERE LIVROS.CODIGO_AUTOR = AUTORES.CODIGO_AUTOR 
AND GENERO='Policial' AND MORADA LIKE '%Coimbra' ;

SELECT AUTORES.NOME
FROM AUTORES, LIVROS
WHERE LIVROS.CODIGO_AUTOR = AUTORES.CODIGO_AUTOR 
AND AUTORES.GENERO_PREFERIDO = LIVROS.GENERO;

SELECT LIVROS.TITULO, LIVROS.PRECO_TABELA
FROM LIVROS, VENDAS, CLIENTES
WHERE VENDAS.CODIGO_CLIENTE = CLIENTES.CODIGO_CLIENTE 
AND VENDAS.CODIGO_LIVRO = LIVROS.CODIGO_LIVRO 
AND MORADA LIKE '%Coimbra';

SELECT AUTORES.NOME
FROM AUTORES, LIVROS, VENDAS, CLIENTES
WHERE AUTORES.CODIGO_AUTOR = LIVROS.CODIGO_AUTOR 
AND LIVROS.CODIGO_LIVRO = VENDAS.CODIGO_LIVRO
AND VENDAS.CODIGO_CLIENTE = CLIENTES.CODIGO_CLIENTE 
AND AUTORES.N_CONTRIBUINTE = CLIENTES.N_CONTRIBUINTE;

SELECT AUTORES.NOME, LIVROS.TITULO, LIVROS.GENERO
FROM AUTORES, LIVROS
WHERE LIVROS.CODIGO_AUTOR = AUTORES.CODIGO_AUTOR 
AND AUTORES.GENERO_PREFERIDO != LIVROS.GENERO
ORDER BY AUTORES.NOME ASC;

SELECT LIVROS.TITULO, "Rendeu" ???
FROM LIVROS
WHERE LIVROS.CODIGO_LIVRO = VENDAS.CODIGO_LIVRO
AND ????