------ AULA 4 2016/2017

 
SELECT TITULO
FROM LIVROS
WHERE DATA_EDICAO LIKE '11%';

SELECT to_char(sysdate, 'DD-MM-YYYY')" Data Actual", to_char(sysdate, 'HH24:MI:SS') "Hora Actual"
FROM DUAL;

SELECT TITULO, PRECO_TABELA
FROM LIVROS
WHERE SYSDATE - DATA_EDICAO < 1000;  /*COM 80 NAO APARECE POR JA ESTARMOS EM OUTUBRO"*/

SELECT DATA_VENDA, MORADA
FROM VENDAS, CLIENTES
WHERE VENDAS.CODIGO_CLIENTE=CLIENTES.CODIGO_CLIENTE;

SELECT TITULO
FROM LIVROS, VENDAS, CLIENTES
WHERE LIVROS.CODIGO_LIVRO=VENDAS.CODIGO_LIVRO
AND VENDAS.CODIGO_CLIENTE=CLIENTES.CODIGO_CLIENTE
AND VENDAS.DATA_VENDA BETWEEN '14.01.01' AND '14.01.02'  /*NAO HA DATAS VENDAS ENTRE AS DATAS PEDIDAS*/
AND CLIENTES.MORADA LIKE '%Lisboa';

SELECT LIVROS.TITULO, LIVROS.GENERO, LIVROS.DATA_EDICAO, VENDAS.DATA_VENDA
FROM LIVROS, VENDAS
WHERE LIVROS.CODIGO_LIVRO = VENDAS.CODIGO_LIVRO
AND MONTHS_BETWEEN(VENDAS.DATA_VENDA,LIVROS.DATA_EDICAO) < 1
AND UPPER(GENERO) = 'INFORMÁTICA';