------ AULA 6 2016/2017

select COUNT(*)"Total de livros de Informatica"
from LIVROS
where GENERO='Informática';

select COUNT(*) "Total de livros", ROUND( AVG(PRECO_TABELA),2) "Preço medio" ,SUM(UNIDADES_VENDIDAS) "Total livros vendidos" 
FROM LIVROS;

SELECT GENERO, COUNT(*) "Quantidade"
FROM LIVROS
GROUP BY GENERO
ORDER BY GENERO;

SELECT TITULO, MIN(PRECO_UNITARIO) "Minimo" ,MAX(PRECO_UNITARIO) "Maximo", ROUND(AVG(PRECO_UNITARIO),2) "Medio"
FROM LIVROS,VENDAS
WHERE LIVROS.CODIGO_LIVRO=VENDAS.CODIGO_LIVRO 
AND GENERO='Informática'
GROUP BY TITULO;

SELECT GENERO, MAX(PRECO_TABELA) "Diferenca"
FROM LIVROS
GROUP BY GENERO
MINUS
SELECT GENERO, MIN(PRECO_TABELA)
FROM LIVROS
GROUP BY GENERO;

SELECT DISTINCT TITULO, PRECO_TABELA "Preco",QUANTIDADE "Num_Vendidos", QUANTIDADE*PRECO_TABELA "Receita Esperada", PRECO_UNITARIO*QUANTIDADE "Receita Efetiva"
FROM LIVROS,VENDAS
WHERE LIVROS.CODIGO_LIVRO=VENDAS.CODIGO_LIVRO;

SELECT GENERO, ROUND(AVG(PRECO_TABELA),0) "Preço Tabela"
FROM LIVROS
GROUP BY GENERO
HAVING COUNT(CODIGO_LIVRO) >= 4
ORDER BY AVG(PRECO_TABELA);

SELECT AUTORES.NOME, MIN(PRECO_TABELA) "Preço minimo"
FROM AUTORES, LIVROS
WHERE AUTORES.CODIGO_AUTOR=LIVROS.CODIGO_AUTOR
GROUP BY NOME
HAVING MIN(PRECO_TABELA) > 30;

SELECT CLIENTES.CODIGO_CLIENTE "Codigo cliente", CLIENTES.NOME "Nome", SUM(QUANTIDADE) "Nº Livros", ROUND(AVG(PRECO_UNITARIO),2) "Preço medio", COUNT(CODIGO_AUTOR) "Nº Autores diferentes"
FROM CLIENTES, VENDAS, LIVROS
WHERE CLIENTES.CODIGO_CLIENTE=VENDAS.CODIGO_CLIENTE
AND VENDAS.CODIGO_LIVRO=LIVROS.CODIGO_LIVRO
AND CLIENTES.MORADA like '%Lisboa'
GROUP BY CLIENTES.CODIGO_CLIENTE, CLIENTES.NOME
HAVING SUM(QUANTIDADE) > 3;

SELECT AUTORES.NOME, DECODE(COUNT(LIVROS.TITULO),0,'NENHUM', COUNT(LIVROS.TITULO)) "Num Livros"
FROM AUTORES, LIVROS
WHERE LIVROS.CODIGO_AUTOR=AUTORES.CODIGO_AUTOR
GROUP BY AUTORES.NOME;


SELECT COUNT(*) "Total de Livros"
FROM LIVROS;

--nao funciona
SELECT MIN(PRECO_TABELA) "Minimo" ,MAX(PRECO_TABELA) "Maximo", ROUND(AVG(PRECO_TABELA),2) "Medio"
FROM EDITORAS, LIVROS
WHERE LIVROS.CODIGO_EDITORA=EDITORAS.CODIGO_EDITORA
AND EDITORAS.NOME = 'FCA';

SELECT GENERO, COUNT(*) "Quantidade"
FROM LIVROS, AUTORES
WHERE LIVROS.CODIGO_AUTOR=AUTORES.CODIGO_AUTOR
AND AUTORES.NOME like '%a%'
OR AUTORES.MORADA like '%Coimbra'
GROUP BY GENERO
ORDER BY GENERO;

--AJUDAS:
SELECT NOME, MORADA
FROM AUTORES
WHERE AUTORES.NOME like '%a%'
OR AUTORES.MORADA like '%Coimbra';

SELECT GENERO, COUNT(*) "Quantidade"
FROM LIVROS
GROUP BY GENERO
ORDER BY GENERO;
--