-- Ficha 9 

-- ex1
CREATE TABLE AUTORES2 (
  CODIGO_AUTOR NUMBER(4)
       CONSTRAINT PK_AUTORES2 PRIMARY KEY,
  NOME VARCHAR(30)
	NOT NULL
    CONSTRAINT CK_NOME_MAIS CHECK(NOME=UPPER(NOME) ),
  N_CONTRIBUINTE NUMBER(9)
	CONSTRAINT UK_NIF UNIQUE,
  MORADA VARCHAR (50),
  IDADE NUMBER (3)
	CONSTRAINT CK_IDADE
	CHECK(IDADE BETWEEN 0 AND 200),
  SEXO CHAR (1)
	CHECK(SEXO IN ('F','M')),
  NACIONALIDADE VARCHAR (20),
  GENERO_PREFERIDO VARCHAR (20)
  );
  
  
  -- ex2
CREATE TABLE AVALIACOES (
  CODIGO_LIVRO NUMBER(4),
  CODIGO_CLIENTE NUMBER(4),
  NOTA NUMBER(3),
  CONSTRAINT PK_AVALIA 
    PRIMARY KEY(CODIGO_LIVRO, CODIGO_CLIENTE),
  CONSTRAINT FK_AVALIA_LIVRO
    FOREIGN KEY(CODIGO_LIVRO)
    REFERENCES LIVROS(CODIGO_LIVRO),
  CONSTRAINT CK_NOTA CHECK (NOTA BETWEEN 1 AND 5 )
  );
  
  
-- ex3
CREATE TABLE LIVROS_BACKUP AS
  SELECT 
  CODIGO_LIVRO, CODIGO_EDITORA, CODIGO_AUTOR, TITULO, ISBN,
  UPPER(GENERO) AS GENERO,
  PRECO_TABELA, PAGINAS, QUANT_EM_STOCK,
  UNIDADES_VENDIDAS, DATA_EDICAO
FROM LIVROS ;


-- ex4
ALTER TABLE LIVROS_BACKUP
ADD CONSTRAINT PK_LIVR_BKP
    PRIMARY KEY(CODIGO_LIVRO);
ALTER TABLE LIVROS_BACKUP
ADD CONSTRAINT FK_LIVRO_AUTOR
    FOREIGN KEY(CODIGO_AUTOR)
    REFERENCES AUTORES(CODIGO_AUTOR);
ALTER TABLE LIVROS_BACKUP
ADD CONSTRAINT FK_LIVRO_EDITORA
    FOREIGN KEY(CODIGO_EDITORA)
    REFERENCES AUTORES(CODIGO_EDITORA);
    
    
-- ex5
INSERT INTO LIVROS_BACKUP VALUES(51,
    (SELECT CODIGO_EDITORA
    FROM EDITORAS WHERE NOME LIKE 'FCA%'),
    (SELECT CODIGO_AUTOR 
    FROM AUTORES WHERE NOME='Sérgio Sousa'),
    'INFORMÁTICA PARA TODOS' , 'INFORMÁTICA',
    24, 430, NULL, 0, SYSDATE);
    

-- ex6
INSERT INTO AUTORES2 (CODIGO_AUTOR, NOME, N_CONTRIBUINTE)
  VALUES (45, 'JOSÉ DE MAGALHÃES', 77665544);


-- ex7
DELETE FROM LIVROS_BACKUP
WHERE CODIGO_LIVRO = 51;


-- ex8 
UPDATE LIVROS_BACKUP
SET PRECO_TABELA = PRECO_TABELA * 1.1
WHERE GENERO= 'AVENTURA';




