-- Aula Prática 23Out2018
-- ficha 4: ex9 ex10 exd
-- ficha 5

-- f4 ex10
SELECT NOME, ''||COUNT(CODIGO_LIVRO) NUM_LIVROS
FROM AUTORES A, LIVROS L
WHERE A.CODIGO_AUTOR = L.CODIGO_AUTOR 
GROUP BY NOME
UNION
SELECT NOME, 'NENHUM'
FROM AUTORES A
MINUS
SELECT NOME, 'NENHUM'
FROM AUTORES A, LIVROS L
WHERE A.CODIGO_AUTOR = L.CODIGO_AUTOR;

-- f4 ex10 com alter join
SELECT NOME, DECODE(COUNT(CODIGO_AUTOR)),0,'NENHUM', COUNT(LIVRO) -- FALTAM COISAS
FROM AUTORES A, LIVROS L
WHERE A.CODIGO_AUTOR = L.CODIGO_AUTOR (+)
GROUP BY NOME;



---------------- FICHA 5 ------------------                        

--f3 ex1.a 
SELECT TITULO , MAXIMO
FROM LIVROS, (SELECT MAX(PRECO_TABELA) MAXIMO 
              FROM LIVROS
              WHERE UPPER(GENERO)= 'INFORMÉTICA') X
WHERE PRECO_TABELA = MAXIMO;
AND UPPER(GENERO)= 'INFORMÁTICA';

-- f5 ex2
SELECT DISTINCT NOME 
FROM LIVROS L , AUTORES A
WHERE L.CODIGO_AUTOR = A.CODIGO_AUTOR 
AND PAGINAS >
             (SELECT AVG(PAGINA) MEDIA 
              FROM LIVROS);
        
-- f5 ex3
SELECT NOME
FROM AUTORES A, LIVROS L 
WHERE A.CODIGO_AUTOR = L.CODIGO_AUTOR
GROUP BY NOME 
HAVING COUNT(TITULO) >

(   SELECT AVG(NLIVROS) MEDIA
    FROM (SELECT CODIGO_AUTOR, COUNT(CODIGO_LIVRO) NLIVROS
          FROM LIVROS 
          GROUP BY CODIGO_AUTOR ) )
        




















